
--FABRICANTE
CREATE TABLE FABRICANTE(
        COD_FAB INTEGER PRIMARY KEY,
        NOME_FAB VARCHAR(50) NOT NULL,
        TIPO_PRODUTO
)
--DEPARTAMENTO
CREATE TABLE DEPARTAMENTO(
        CAD_DEPTO NUMBER(3) PRIMARY KEY,
        NOME_DEPTO VARCHAR(30) NOT NULL,
        RAMAL_DEPTO CHAR(5),
)

--ITEM PATRIMONIAL
CREATE TABLE ITEM_PATRIMONIAL(
        NUM_PATRI INTEGER PRIMARY KEY,
        DATA_AQUISICAO DATE NOT NULL,
        NOTA_FISCAL VARCHAR NOT NULL,
        VALOR DOUBLE NOT NULL,
        GARANTIA NUMBER(5) NOT NULL,
        TIPO_EQUIP CHAR(8) NOT NULL,
        COD_FAB INTEGER REFERENCES FABRICANTE,
        COD_DEPTO NUMBER(3) REFERENCES DEPARTAMENTO
)
